---
kind: List
apiVersion: v1
metadata: {}
items:
- kind: ServiceAccount
  ApiVersion: v1
  metadata:
    name: skydive
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: skydive-analyzer
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: skydive
          tier: analyzer
      spec:
        containers:
        - name: skydive-analyzer
          image: skydive/skydive
          args:
          - analyzer
          - --listen=0.0.0.0:8082
          ports:
          - containerPort: 8082
          - containerPort: 8082
            protocol: UDP
          - containerPort: 2379
          env:
          - name: SKYDIVE_ANALYZER_STORAGE
            value: elasticsearch
          - name: SKYDIVE_GRAPH_BACKEND
            value: elasticsearch
          volumeMounts:
          - mountPath: /tmp
            name: skydive-tmp-1
        - name: skydive-elasticsearch
          image: elasticsearch:2.4.1
          ports:
          - containerPort: 9200
          volumeMounts:
          - mountPath: /usr/share/elasticsearch/data
            name: elasticsearch-volume-1
        volumes:
        - emptyDir: {}
          name: elasticsearch-volume-1 
        - emptyDir: {}
          name: skydive-tmp-1
- kind: Service
  ApiVersion: v1
  metadata:
    name: skydive-analyzer
    labels:
      app: skydive-analyzer
  spec:
    type: NodePort
    ports:
    - port: 8082
      name: api
    - port: 8082
      name: protobuf
      protocol: UDP
    - port: 2379
      name: etcd
    - port: 9200
      name: es
    selector:
      app: skydive
      tier: analyzer
